server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

spring:
  application:
    name: snapshotmanager

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
