server:
  port: 8282

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

spring:
  application:
    name: snapshot
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user
      password: user-123
      database: snapshots
      authentication-database: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
