spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://db:3306/recorddb
    username: user
    password: secret
    driverClassName: com.mysql.cj.jdbc.Driver