server:
  port: 8181

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

spring:
  application:
    name: storage
  datasource:
    url: jdbc:mysql://localhost:3306/storage
    username: user
    password: user-123
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
